jobs:
  auto_close_issues:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Automatically close issues that don't follow the issue template
      uses: roots/issue-closer@v1.1
      with:
        issue-close-message: '@${issue.user.login}, this issue is being automatically
          closed because it does not follow the issue template.'
        issue-pattern: .*please make sure that this issue is related to the app itself.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
on:
  repository_dispatch:
    types: trigger-ga___close_issues.yml
